var playerNames = [
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Neymar",
  "Luis Suárez",
  "Robert Lewandowski",
  "Thomas Müller",
  "Zlatan Ibrahimovic",
  "Manuel Neuer",
  "Sergio Agüero",
  "Alexis Sánchez",
  "Paul Pogba",
  "Andres Iniesta",
  "Eden Hazard",
  "Kevin De Bruyne",
  "Arturo Vidal",
  "Gareth Bale",
  "Carlos Tevez",
  "David de Gea",
  "James Rodríguez",
  "Ivan Rakitic",
  "Philipp Lahm",
  "Arjen Robben",
  "David Alaba",
  "Sergio Busquets",
  "Javier Mascherano",
  "Mesut Ozil",
  "Pierre-Emerick Aubameyang",
  "Antoine Griezmann",
  "Yaya Toure",
  "David Silva",
  "Luka Modric",
  "Douglas Costa",
  "Karim Benzema",
  "Gianluigi Buffon",
  "Toni Kroos",
  "Thibaut Courtois",
  "Sergio Ramos",
  "Harry Kane",
  "Angel di Maria",
  "Diego Godin",
  "Thiago Silva",
  "Andrea Pirlo",
  "Marco Verratti",
  "Gerard Pique",
  "Jerome Boateng",
  "Philippe Coutinho",
  "Alvaro Morata",
  "Gonzalo Higuain",
  "Xabi Alonso",
  "Marco Reus",
  "Diego Costa",
  "Willian",
  "Blaise Matuidi",
  "Edinson Cavani",
  "Miralem Pjanic",
  "Raphael Varane",
  "Vincent Kompany",
  "Dani Alves",
  "Hulk",
  "Wayne Rooney",
  "Alexandre Lacazette",
  "Raheem Sterling",
  "Cesc Fabregas",
  "Yacine Brahimi",
  "Carlos Bacca",
  "Anthony Martial",
  "Keylor Navas",
  "Jamie Vardy",
  "Mohamed Salah",
  "Koke",
  "Giorgio Chiellini",
  "Jordi Alba",
  "Yevhen Konoplyanka",
  "Bastian Schweinsteiger",
  "Mats Hummels",
  "Franck Ribery",
  "Henrikh Mkhitaryan",
  "Arda Turan",
  "Petr Cech",
  "Mario Gotze",
  "Thiago Alcantara",
  "Mauro Icardi",
  "Nolito",
  "Claudio Bravo",
  "Javier Pastore",
  "Memphis Depay",
  "Juan Mata",
  "Marcelo",
  "Alex Teixeira",
  "Dimitri Payet",
  "Isco",
  "Leonardo Bonucci",
  "Carlos Sanchez",
  "Sebastian Giovinco",
  "Santi Cazorla",
  "Francesco Totti",
  "Riyad Mahrez",
  "Andriy Yarmolenko",
  "Nemanja Matic",
  "Laurent Koscielny"
];

// Will give me a random player from our 'playerNames array'
function randomPlayerSelector() {
  return playerNames[Math.floor(Math.random() * playerNames.length + 1)];
}
